<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Corpo para MiniFramework</title>
        
        <link href="css/style.css" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    </head>
    <body>
        <!--Container principal-->
        <div class="container-fluid">
            
            <!--Menu-->
            <nav class="navbar navbar-expand-lg navbar-light menu">
                <a class="navbar-brand text-primary" href="#">SOCIUS - Plataforma Evangélica</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class=" collapse navbar-collapse" id="navbarNav" >
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-danger" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                GERENCIAR
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Membros</a>
                                <a class="dropdown-item" href="#">Usuários</a>
                                <a class="dropdown-item" href="#">Agenda</a>
                                <a class="dropdown-item" href="#">Agenda</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled text-danger" href="#" tabindex="-1" aria-disabled="true">FINANCEIRO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="#">PESQUISAR</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="#">RELATORIOS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="#">CARTAS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="#">FERRAMENTAS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="#">SAIR</a>
                        </li>

                    </ul>
                </div>
            </nav>
            
            <!--Corpo do Container-->
            <div class="container-fluid">
                <div class="">
                    <p class="text-right">Bem vindo Fulano e Tal</p>
                </div>
                
                <div class="container">
                    <div class="row ">
                        <div class="col-sm border border-success rounded notify-painel-1">
                            <div class="text-center border border-success rounded bg-success">
                                <i class="fas fa-calendar-alt"></i> AGENDA DO DIA
                            </div>
                            
                            <hr>
                            
                            <ul>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                            </ul>
                        </div>
                        
                        <div class="col-sm border border-success rounded notify-painel-2">
                            <div class="text-center border border-success rounded bg-info">
                                <i class="fas fa-gift"></i> ANIVERSARIANTES DO DIA
                            </div>
                            
                            <hr>
                            
                            <ul>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                            </ul>
                        </div>
                        
                        <div class="col-sm border border-success rounded notify-painel-3">
                            <div class="text-center border border-success rounded bg-warning">
                                <i class="fas fa-exclamation-triangle"></i> NOTIFICAÇÕES
                            </div>
                            
                            <hr>
                            
                            <ul>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                                <li><i class="fas fa-calendar-alt"></i> <small>01/04/20 - 19:00hs - CULTOS DE JOVENS - SOLAR 2 </small></li>
                            </ul>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
            
            <!--Rodapé-->
            <footer class="container-fluid footer navbar-fixed-bottom">
                <?php
                $today = date('Y');
                ?>
                <p class="text-center">SOCIUS - Plataforma Evangélica - Todos os direitos reservados - <?php echo $today?></p>
                <small><p class="text-center">Desenvolvido por: <a href="http://www.hq-innit.com.br">HQ-InnIT</a></p></small>
            </footer>
            
        </div>
    </body>
</html>
