<div class="container-fluid"">
    <div class="row">
        <div class="col-md-6 container">
            <img style="width: 500px;" src="/image/img-logo-socius.png" alt="Logotipo SOCIUS"/>
        </div>
        <div class="col-md-4 ">
            <div class="d-flex justify-content-center mt-5">
                <div class="card" style="width: 36rem;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col text-center">
                                <h2>Acesso ao Sistema</h2>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">

                                <form action="/autenticar" method="post">

                                    <div class="form-group">
                                        <input type="text" value="" name="email" class="form-control" placeholder="E-mail">
                                    </div>

                                    <div class="form-group">
                                        <input type="password" value="" name="senha" class="form-control" placeholder="Senha">
                                    </div>
                                    
                                    <button type="submit" class="btn btn-primary btn-block">Entrar</button><br>
                                </form>
                                
                                <a href="#"><button class="btn btn-info btn-block">Esqueci minha senha</button></a>
                                
                                
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>    
    </div>

</div>
